set package and namespace to Kentico.Xperience.Disqus.Widget
Kentico/xperience-disqus pull request #8
Opened 2022-08-25 19:43 UTC by kentico-ericd

### Motivation

With the release of the XbK Disqus integration, the NuGet package naming conventions need to be changed. The KX13 package will be named `Kentico.Xperience.Disqus.Widget.KX13` and the XbK package will be named `Kentico.Xperience.Disqus.Widget`.

### Checklist

- [X] Code follows coding conventions held in this repo
- [X] Docs have been updated (if applicable)
- [X] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

2022-08-26 08:47 UTC, KubaOczko requested changes
The namespace, identifier and other part of code should kept unchanged. We want to just change the nuget package name.

2022-08-26 18:28 UTC, kentico-ericd reviewed
Reverted namespace and identifier changes

2022-09-05 18:10 UTC, kentico-ericd commented on src/Kentico.Xperience.Disqus.csproj
> +		<TargetFramework>netcoreapp6</TargetFramework>
done

2022-09-05 18:11 UTC, kentico-ericd commented on src/Kentico.Xperience.Disqus.csproj
> +		<None Include="..\img\icon.png" Pack="true" PackagePath="" />
the icon has been updated

2022-09-06 06:25 UTC, KubaOczko approved these changes

2022-09-06 06:26 UTC, merged